### ISSUE TITLE
Could the tiktoken dependency be optional?

### ISSUE THREAD

**Issue by carlos-alberto** [dzhng/llm-api#6]
We're deploying into cloudflare, and tiktoken is a large library. We don't particularly need the [token error check](https://github.com/dzhng/llm-api#-token-errors), so having a way to only optionally include the large library would be great.

**Comment by dzhng** [comment]
sorry but it's a bit tricky to remove and I don't have the time right now to implement & properly test. I do think this check is getting less relevant over time as large context models becomes prevalent, so will rework at some point, but going to close this for now.
